---
- name: Set fallback language
  lineinfile:
    dest: "{{ idp_home }}/conf/idp.properties"
    line: "idp.ui.fallbackLanguages= {{ idp_ui_fallbackLanguages }}"
    regexp: "^idp.ui.fallbackLanguages"
  notify: "{{ 'Restart tomcat'  if ansible_virtualization_type != 'docker' else 'Restart tomcat in docker' }}"
  tags:
    - shibboleth
    - idp_customise

- name: Apply custom templates
  copy:
    src: "{{ idp_custom_templates_path }}"
    dest: "{{ idp_home }}/views/"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  when: idp_custom_templates_path is defined
  tags:
    - shibboleth
    - idp_customise

- name: Apply custom css
  copy:
    src: "{{ idp_custom_css_path }}"
    dest: "{{ idp_home }}/webapp/css/"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  when: idp_custom_css_path is defined
  tags:
    - shibboleth
    - idp_customise

- name: Apply custom images
  copy:
    src: "{{ idp_custom_images_path }}"
    dest: "{{ idp_home }}/webapp/images/"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  when: idp_custom_images_path is defined
  tags:
    - shibboleth
    - idp_customise

- name: Apply custom messages
  copy:
    src: "{{ idp_custom_messages_path }}"
    dest: "{{ idp_home }}/messages"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  when: idp_custom_messages_path is defined
  tags:
    - shibboleth
    - idp_customise
